/**
 * @pocket/cli - Deploy Command
 *
 * Generates deployment configuration and entry point files
 * for supported platforms without actually deploying.
 *
 * @module @pocket/cli/commands
 */

/**
 * Supported deployment providers.
 */
export type DeployProvider = 'cloudflare' | 'deno' | 'vercel';

/**
 * Deploy command options.
 */
export interface DeployOptions {
  /** Target deployment provider */
  provider: DeployProvider;
  /** Output directory for generated config files */
  outputDir?: string;
  /** Project name (used in config files) */
  projectName?: string;
  /** Entry point filename */
  entryPoint?: string;
}

/**
 * Generated deployment file.
 */
export interface DeployFile {
  /** File path relative to output directory */
  path: string;
  /** File content */
  content: string;
}

/**
 * Result of the deploy command.
 */
export interface DeployResult {
  /** Provider used */
  provider: DeployProvider;
  /** Files generated */
  files: DeployFile[];
  /** Deployment instructions */
  instructions: string[];
}

/**
 * DeployCommand generates deployment configuration and entry points
 * for various edge platforms.
 */
export class DeployCommand {
  /**
   * Execute the deploy command.
   *
   * Generates platform-specific configuration files and a sync-server
   * entry point, then returns deployment instructions.
   *
   * @param options - Deployment options
   * @returns Generated files and deployment instructions
   */
  execute(options: DeployOptions): DeployResult {
    const projectName = options.projectName ?? 'pocket-app';
    const outputDir = options.outputDir ?? '.';

    switch (options.provider) {
      case 'cloudflare':
        return this.generateCloudflare(projectName, outputDir);
      case 'deno':
        return this.generateDeno(projectName, outputDir);
      case 'vercel':
        return this.generateVercel(projectName, outputDir);
      default:
        throw new Error(`Unsupported provider: ${String(options.provider)}`);
    }
  }

  private generateCloudflare(projectName: string, outputDir: string): DeployResult {
    const configContent = [
      `name = "${projectName}"`,
      `main = "src/worker.ts"`,
      `compatibility_date = "${new Date().toISOString().slice(0, 10)}"`,
      ``,
      `[vars]`,
      `POCKET_DB = "${projectName}"`,
      ``,
      `[[kv_namespaces]]`,
      `binding = "POCKET_KV"`,
      `id = "your-kv-namespace-id"`,
      ``,
      `[durable_objects]`,
      `bindings = [`,
      `  { name = "POCKET_DO", class_name = "PocketDurableObject" }`,
      `]`,
      ``,
    ].join('\n');

    const entryContent = [
      `/**`,
      ` * Pocket sync server entry point for Cloudflare Workers.`,
      ` *`,
      ` * Generated by @pocket/cli`,
      ` */`,
      ``,
      `import { createEdgeSyncServer } from '@pocket/storage-edge';`,
      `import { createCloudflareKVStorage } from '@pocket/storage-edge/cloudflare';`,
      ``,
      `export default {`,
      `  async fetch(request: Request, env: Record<string, unknown>): Promise<Response> {`,
      `    const storage = createCloudflareKVStorage({ namespace: env.POCKET_KV });`,
      `    const server = createEdgeSyncServer({ storage });`,
      `    return server.handleRequest(request);`,
      `  },`,
      `};`,
      ``,
    ].join('\n');

    return {
      provider: 'cloudflare',
      files: [
        { path: `${outputDir}/wrangler.toml`, content: configContent },
        { path: `${outputDir}/src/worker.ts`, content: entryContent },
      ],
      instructions: [
        'Install Wrangler CLI: npm install -g wrangler',
        'Authenticate: wrangler login',
        `Create KV namespace: wrangler kv:namespace create "POCKET_KV"`,
        'Update the KV namespace ID in wrangler.toml',
        'Deploy: wrangler deploy',
      ],
    };
  }

  private generateDeno(projectName: string, outputDir: string): DeployResult {
    const configContent = JSON.stringify(
      {
        tasks: {
          start: 'deno run --allow-net --allow-read --allow-env src/server.ts',
          dev: 'deno run --watch --allow-net --allow-read --allow-env src/server.ts',
        },
        imports: {
          '@pocket/storage-edge': 'npm:@pocket/storage-edge',
        },
      },
      null,
      2
    ) + '\n';

    const entryContent = [
      `/**`,
      ` * Pocket sync server entry point for Deno.`,
      ` *`,
      ` * Generated by @pocket/cli`,
      ` */`,
      ``,
      `import { createEdgeSyncServer } from '@pocket/storage-edge';`,
      `import { createDenoKVStorage } from '@pocket/storage-edge/deno';`,
      ``,
      `const storage = createDenoKVStorage({});`,
      `const server = createEdgeSyncServer({ storage });`,
      ``,
      `Deno.serve({ port: 8787 }, (request: Request) => {`,
      `  return server.handleRequest(request);`,
      `});`,
      ``,
      `console.log('Pocket sync server running on http://localhost:8787');`,
      ``,
    ].join('\n');

    return {
      provider: 'deno',
      files: [
        { path: `${outputDir}/deno.json`, content: configContent },
        { path: `${outputDir}/src/server.ts`, content: entryContent },
      ],
      instructions: [
        'Install Deno: https://deno.land/manual/getting_started/installation',
        'Run locally: deno task start',
        'Deploy to Deno Deploy: deployctl deploy --project=' + projectName + ' src/server.ts',
      ],
    };
  }

  private generateVercel(projectName: string, outputDir: string): DeployResult {
    const configContent = JSON.stringify(
      {
        name: projectName,
        functions: {
          'api/sync.ts': {
            runtime: 'edge',
          },
        },
        routes: [
          { src: '/api/sync(.*)', dest: '/api/sync.ts' },
        ],
      },
      null,
      2
    ) + '\n';

    const entryContent = [
      `/**`,
      ` * Pocket sync server entry point for Vercel Edge Functions.`,
      ` *`,
      ` * Generated by @pocket/cli`,
      ` */`,
      ``,
      `import { createEdgeSyncServer } from '@pocket/storage-edge';`,
      `import { createVercelKVStorage } from '@pocket/storage-edge/vercel';`,
      ``,
      `const storage = createVercelKVStorage({`,
      `  url: process.env.KV_REST_API_URL!,`,
      `  token: process.env.KV_REST_API_TOKEN!,`,
      `});`,
      `const server = createEdgeSyncServer({ storage });`,
      ``,
      `export const config = { runtime: 'edge' };`,
      ``,
      `export default async function handler(request: Request): Promise<Response> {`,
      `  return server.handleRequest(request);`,
      `}`,
      ``,
    ].join('\n');

    return {
      provider: 'vercel',
      files: [
        { path: `${outputDir}/vercel.json`, content: configContent },
        { path: `${outputDir}/api/sync.ts`, content: entryContent },
      ],
      instructions: [
        'Install Vercel CLI: npm install -g vercel',
        'Link project: vercel link',
        'Add KV store: vercel env add KV_REST_API_URL && vercel env add KV_REST_API_TOKEN',
        'Deploy: vercel deploy',
      ],
    };
  }
}

/**
 * Create a DeployCommand instance.
 */
export function createDeployCommand(): DeployCommand {
  return new DeployCommand();
}
