/**
 * Edge deploy command for the Pocket CLI.
 *
 * Generates deployment configurations and project scaffolds for
 * edge runtime platforms (Cloudflare Workers, Deno Deploy, Vercel Edge).
 *
 * @module commands/edge-deploy
 */

/** Supported edge platforms */
export type EdgePlatform = 'cloudflare' | 'deno' | 'vercel' | 'bun';

/** Edge deploy command options */
export interface EdgeDeployOptions {
  /** Target edge platform */
  readonly platform: EdgePlatform;
  /** Project name */
  readonly projectName?: string;
  /** Output directory for generated files */
  readonly outputDir?: string;
  /** Primary region */
  readonly region?: string;
  /** Enable sync server */
  readonly enableSync?: boolean;
}

/** Result of edge deploy command */
export interface EdgeDeployResult {
  readonly success: boolean;
  readonly platform: EdgePlatform;
  readonly generatedFiles: readonly GeneratedDeployFile[];
  readonly instructions: readonly string[];
}

/** A generated deployment file */
export interface GeneratedDeployFile {
  readonly path: string;
  readonly content: string;
  readonly description: string;
}

const CLOUDFLARE_WORKER_TEMPLATE = `// Generated by @pocket/cli — Pocket Edge Sync Server
import { createEdgeSyncServer } from '@pocket/storage-edge';
import { createCloudflareKVStorage } from '@pocket/storage-edge/cloudflare';

export default {
  async fetch(request, env) {
    const storage = createCloudflareKVStorage({ namespace: env.POCKET_KV });
    const server = createEdgeSyncServer({ storage });
    return server.handleRequest(request);
  },
};
`;

const CLOUDFLARE_WRANGLER_TEMPLATE = (name: string) => `# Generated by @pocket/cli
name = "${name}"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "POCKET_KV"
id = ""
`;

const DENO_SERVER_TEMPLATE = `// Generated by @pocket/cli — Pocket Edge Sync Server
import { createEdgeSyncServer } from '@pocket/storage-edge';
import { createDenoKVStorage } from '@pocket/storage-edge/deno';

const kv = await Deno.openKv();
const storage = createDenoKVStorage({ kv });
const server = createEdgeSyncServer({ storage });

Deno.serve({ port: 8000 }, (request) => server.handleRequest(request));
`;

const VERCEL_EDGE_TEMPLATE = `// Generated by @pocket/cli — Pocket Edge Sync Server
import { createEdgeSyncServer } from '@pocket/storage-edge';
import { createVercelKVStorage } from '@pocket/storage-edge/vercel';

export const config = { runtime: 'edge' };

const storage = createVercelKVStorage({});
const server = createEdgeSyncServer({ storage });

export default async function handler(request) {
  return server.handleRequest(request);
}
`;

/**
 * Generate edge deployment configuration files.
 *
 * @example
 * ```typescript
 * import { edgeDeploy } from '@pocket/cli';
 *
 * const result = edgeDeploy({
 *   platform: 'cloudflare',
 *   projectName: 'my-pocket-app',
 * });
 *
 * for (const file of result.generatedFiles) {
 *   // Write file.content to file.path
 * }
 * ```
 */
export function edgeDeploy(options: EdgeDeployOptions): EdgeDeployResult {
  const name = options.projectName ?? 'pocket-edge';
  const outDir = options.outputDir ?? '.';

  switch (options.platform) {
    case 'cloudflare':
      return {
        success: true,
        platform: 'cloudflare',
        generatedFiles: [
          { path: `${outDir}/src/worker.ts`, content: CLOUDFLARE_WORKER_TEMPLATE, description: 'Cloudflare Worker entry point' },
          { path: `${outDir}/wrangler.toml`, content: CLOUDFLARE_WRANGLER_TEMPLATE(name), description: 'Wrangler configuration' },
        ],
        instructions: [
          'Install dependencies: npm install @pocket/storage-edge',
          'Configure KV namespace ID in wrangler.toml',
          'Deploy: npx wrangler deploy',
        ],
      };

    case 'deno':
      return {
        success: true,
        platform: 'deno',
        generatedFiles: [
          { path: `${outDir}/main.ts`, content: DENO_SERVER_TEMPLATE, description: 'Deno Deploy entry point' },
        ],
        instructions: [
          'Deploy to Deno Deploy: deployctl deploy --project=my-project main.ts',
        ],
      };

    case 'vercel':
      return {
        success: true,
        platform: 'vercel',
        generatedFiles: [
          { path: `${outDir}/api/sync.ts`, content: VERCEL_EDGE_TEMPLATE, description: 'Vercel Edge Function' },
        ],
        instructions: [
          'Install: npm install @pocket/storage-edge',
          'Configure Vercel KV in project settings',
          'Deploy: vercel deploy',
        ],
      };

    case 'bun':
      return {
        success: true,
        platform: 'bun',
        generatedFiles: [
          {
            path: `${outDir}/server.ts`,
            content: `// Generated by @pocket/cli — Pocket Bun Sync Server
import { createEdgeSyncServer } from '@pocket/storage-edge';
import { createBunSQLiteStorage } from '@pocket/storage-edge/bun';

const storage = createBunSQLiteStorage({ path: './pocket.db' });
const server = createEdgeSyncServer({ storage });

Bun.serve({
  port: 8000,
  fetch: (request) => server.handleRequest(request),
});
`,
            description: 'Bun server entry point',
          },
        ],
        instructions: [
          'Install: bun add @pocket/storage-edge',
          'Run: bun run server.ts',
        ],
      };
  }
}
