import { describe, expect, it } from 'vitest';
import { createApiGenerator } from '../api-generator.js';
import type { SchemaDefinition } from '../types.js';

describe('ApiGenerator', () => {
  const schemaWithRequired: SchemaDefinition = {
    name: 'app',
    version: '1.0.0',
    collections: [
      {
        name: 'users',
        fields: [
          { name: 'email', type: 'string', required: true },
          { name: 'name', type: 'string', required: true },
          { name: 'age', type: 'number' },
        ],
      },
    ],
  };

  const schemaNoRequired: SchemaDefinition = {
    name: 'app',
    version: '1.0.0',
    collections: [
      {
        name: 'items',
        fields: [
          { name: 'label', type: 'string' },
          { name: 'count', type: 'number' },
        ],
      },
    ],
  };

  // ── Express framework ──────────────────────────────────────────────

  describe('express framework', () => {
    const generator = createApiGenerator({ framework: 'express' });

    it('should generate one route file per collection', () => {
      const files = generator.generate(schemaWithRequired);
      expect(files).toHaveLength(1);
      expect(files[0].path).toBe('routes/users.ts');
    });

    it('should set overwrite=true on all files', () => {
      const files = generator.generate(schemaWithRequired);
      expect(files[0].overwrite).toBe(true);
    });

    it('should include auto-generated header', () => {
      const content = generator.generate(schemaWithRequired)[0].content;
      expect(content).toContain('Auto-generated by @pocket/codegen-fullstack');
    });

    it('should import Router from express', () => {
      const content = generator.generate(schemaWithRequired)[0].content;
      expect(content).toContain("import { Router } from 'express';");
    });

    it('should export default router', () => {
      const content = generator.generate(schemaWithRequired)[0].content;
      expect(content).toContain('export default router;');
    });

    it('should generate GET / endpoint', () => {
      const content = generator.generate(schemaWithRequired)[0].content;
      expect(content).toContain("router.get('/', async (req, res)");
      expect(content).toContain('// GET /api/users - List all');
    });

    it('should generate GET /:id endpoint', () => {
      const content = generator.generate(schemaWithRequired)[0].content;
      expect(content).toContain("router.get('/:id', async (req, res)");
      expect(content).toContain('// GET /api/users/:id - Get by ID');
    });

    it('should generate POST / endpoint', () => {
      const content = generator.generate(schemaWithRequired)[0].content;
      expect(content).toContain("router.post('/', async (req, res)");
      expect(content).toContain('// POST /api/users - Create');
    });

    it('should generate PATCH /:id endpoint', () => {
      const content = generator.generate(schemaWithRequired)[0].content;
      expect(content).toContain("router.patch('/:id', async (req, res)");
      expect(content).toContain('// PATCH /api/users/:id - Update');
    });

    it('should generate DELETE /:id endpoint', () => {
      const content = generator.generate(schemaWithRequired)[0].content;
      expect(content).toContain("router.delete('/:id', async (req, res)");
      expect(content).toContain('// DELETE /api/users/:id - Delete');
    });

    it('should include validation for required fields in POST', () => {
      const content = generator.generate(schemaWithRequired)[0].content;
      expect(content).toContain("if (data['email'] === undefined)");
      expect(content).toContain('email is required');
      expect(content).toContain("if (data['name'] === undefined)");
      expect(content).toContain('name is required');
      expect(content).toContain('res.status(400)');
    });

    it('should NOT generate validation when no required fields', () => {
      const content = generator.generate(schemaNoRequired)[0].content;
      expect(content).not.toContain('is required');
      expect(content).not.toContain('status(400)');
    });

    it('should include error handling with 500 status', () => {
      const content = generator.generate(schemaWithRequired)[0].content;
      expect(content).toContain("res.status(500).json({ error: 'Internal server error' })");
    });

    it('should include 201 status for create response', () => {
      const content = generator.generate(schemaWithRequired)[0].content;
      expect(content).toContain('res.status(201).json(data)');
    });

    it('should generate files for multiple collections', () => {
      const schema: SchemaDefinition = {
        name: 'app',
        version: '1',
        collections: [
          { name: 'users', fields: [] },
          { name: 'posts', fields: [] },
          { name: 'comments', fields: [] },
        ],
      };
      const files = generator.generate(schema);
      expect(files).toHaveLength(3);
      expect(files.map((f) => f.path)).toEqual([
        'routes/users.ts',
        'routes/posts.ts',
        'routes/comments.ts',
      ]);
    });

    it('should use collection name in route comments', () => {
      const schema: SchemaDefinition = {
        name: 'app',
        version: '1',
        collections: [{ name: 'products', fields: [] }],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('GET /api/products');
      expect(content).toContain('POST /api/products');
    });
  });

  // ── Next.js framework ──────────────────────────────────────────────

  describe('next framework', () => {
    const generator = createApiGenerator({ framework: 'next' });

    it('should generate route files under app/api/{name}/', () => {
      const files = generator.generate(schemaWithRequired);
      expect(files).toHaveLength(1);
      expect(files[0].path).toBe('app/api/users/route.ts');
    });

    it('should import NextRequest and NextResponse', () => {
      const content = generator.generate(schemaWithRequired)[0].content;
      expect(content).toContain("import { NextRequest, NextResponse } from 'next/server';");
    });

    it('should export GET handler', () => {
      const content = generator.generate(schemaWithRequired)[0].content;
      expect(content).toContain('export async function GET(req: NextRequest)');
    });

    it('should export POST handler', () => {
      const content = generator.generate(schemaWithRequired)[0].content;
      expect(content).toContain('export async function POST(req: NextRequest)');
    });

    it('should return NextResponse.json in GET handler', () => {
      const content = generator.generate(schemaWithRequired)[0].content;
      expect(content).toContain('NextResponse.json([])');
    });

    it('should validate required fields in POST handler', () => {
      const content = generator.generate(schemaWithRequired)[0].content;
      expect(content).toContain("if (data['email'] === undefined)");
      expect(content).toContain('email is required');
      expect(content).toContain('status: 400');
    });

    it('should NOT generate validation when no required fields', () => {
      const content = generator.generate(schemaNoRequired)[0].content;
      expect(content).not.toContain('is required');
      expect(content).not.toContain('status: 400');
    });

    it('should return 201 status for create', () => {
      const content = generator.generate(schemaWithRequired)[0].content;
      expect(content).toContain('status: 201');
    });

    it('should parse request body with req.json()', () => {
      const content = generator.generate(schemaWithRequired)[0].content;
      expect(content).toContain('await req.json()');
    });

    it('should generate route files for multiple collections', () => {
      const schema: SchemaDefinition = {
        name: 'app',
        version: '1',
        collections: [
          { name: 'users', fields: [] },
          { name: 'posts', fields: [] },
        ],
      };
      const files = generator.generate(schema);
      expect(files).toHaveLength(2);
      expect(files[0].path).toBe('app/api/users/route.ts');
      expect(files[1].path).toBe('app/api/posts/route.ts');
    });
  });

  // ── Default framework ──────────────────────────────────────────────

  describe('default framework', () => {
    it('should default to express when no config provided', () => {
      const gen = createApiGenerator();
      const files = gen.generate(schemaWithRequired);
      expect(files[0].path).toBe('routes/users.ts');
      expect(files[0].content).toContain('Router');
    });

    it('should default to express when config has no framework', () => {
      const gen = createApiGenerator({});
      const files = gen.generate(schemaWithRequired);
      expect(files[0].content).toContain('Router');
    });
  });

  // ── Edge cases ─────────────────────────────────────────────────────

  describe('edge cases', () => {
    it('should handle collection with empty fields array', () => {
      const schema: SchemaDefinition = {
        name: 'app',
        version: '1',
        collections: [{ name: 'empty', fields: [] }],
      };
      const expressFiles = createApiGenerator({ framework: 'express' }).generate(schema);
      expect(expressFiles).toHaveLength(1);
      expect(expressFiles[0].content).toContain("router.get('/'");

      const nextFiles = createApiGenerator({ framework: 'next' }).generate(schema);
      expect(nextFiles).toHaveLength(1);
      expect(nextFiles[0].content).toContain('GET');
    });

    it('should handle many required fields', () => {
      const schema: SchemaDefinition = {
        name: 'app',
        version: '1',
        collections: [
          {
            name: 'items',
            fields: [
              { name: 'a', type: 'string', required: true },
              { name: 'b', type: 'string', required: true },
              { name: 'c', type: 'string', required: true },
              { name: 'd', type: 'string', required: true },
            ],
          },
        ],
      };
      const content = createApiGenerator({ framework: 'express' }).generate(schema)[0].content;
      expect(content).toContain('a is required');
      expect(content).toContain('b is required');
      expect(content).toContain('c is required');
      expect(content).toContain('d is required');
    });
  });
});
