import { describe, expect, it } from 'vitest';
import { createHooksGenerator } from '../hooks-generator.js';
import type { SchemaDefinition } from '../types.js';

describe('HooksGenerator', () => {
  const generator = createHooksGenerator();

  const singleCollectionSchema: SchemaDefinition = {
    name: 'app',
    version: '1.0.0',
    collections: [
      {
        name: 'users',
        fields: [
          { name: 'email', type: 'string', required: true },
          { name: 'name', type: 'string' },
          { name: 'age', type: 'number' },
        ],
      },
    ],
  };

  // ── File output ────────────────────────────────────────────────────

  describe('file output', () => {
    it('should generate one file per collection', () => {
      const schema: SchemaDefinition = {
        ...singleCollectionSchema,
        collections: [
          ...singleCollectionSchema.collections,
          { name: 'posts', fields: [{ name: 'title', type: 'string' }] },
          { name: 'comments', fields: [{ name: 'body', type: 'string' }] },
        ],
      };
      const files = generator.generate(schema);
      expect(files).toHaveLength(3);
    });

    it('should name files as hooks/use{CollectionName}.ts', () => {
      const files = generator.generate(singleCollectionSchema);
      expect(files[0].path).toBe('hooks/useUsers.ts');
    });

    it('should set overwrite=true on all files', () => {
      const files = generator.generate(singleCollectionSchema);
      for (const file of files) {
        expect(file.overwrite).toBe(true);
      }
    });
  });

  // ── Header and imports ─────────────────────────────────────────────

  describe('header and imports', () => {
    it('should include auto-generated header', () => {
      const content = generator.generate(singleCollectionSchema)[0].content;
      expect(content).toContain('Auto-generated by @pocket/codegen-fullstack');
    });

    it('should import useState, useEffect, useCallback from react', () => {
      const content = generator.generate(singleCollectionSchema)[0].content;
      expect(content).toContain("import { useState, useEffect, useCallback } from 'react';");
    });
  });

  // ── Interface generation within hook files ─────────────────────────

  describe('inline interface', () => {
    it('should generate interface with capitalized collection name', () => {
      const content = generator.generate(singleCollectionSchema)[0].content;
      expect(content).toContain('export interface Users {');
    });

    it('should include _id in the interface', () => {
      const content = generator.generate(singleCollectionSchema)[0].content;
      expect(content).toContain('_id: string;');
    });

    it('should mark required fields without ?', () => {
      const content = generator.generate(singleCollectionSchema)[0].content;
      expect(content).toContain('email: string;');
      expect(content).not.toContain('email?: string;');
    });

    it('should mark optional fields with ?', () => {
      const content = generator.generate(singleCollectionSchema)[0].content;
      expect(content).toContain('name?: string;');
      expect(content).toContain('age?: number;');
    });

    it('should map all field types correctly', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [
          {
            name: 'items',
            fields: [
              { name: 'a', type: 'string', required: true },
              { name: 'b', type: 'number', required: true },
              { name: 'c', type: 'boolean', required: true },
              { name: 'd', type: 'date', required: true },
              { name: 'e', type: 'object', required: true },
              { name: 'f', type: 'array', required: true },
              { name: 'g', type: 'enum', required: true },
            ],
          },
        ],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('a: string;');
      expect(content).toContain('b: number;');
      expect(content).toContain('c: boolean;');
      expect(content).toContain('d: Date;');
      expect(content).toContain('e: Record<string, unknown>;');
      expect(content).toContain('f: unknown[];');
      expect(content).toContain('g: string;');
    });
  });

  // ── useXxxQuery hook ───────────────────────────────────────────────

  describe('useXxxQuery hook', () => {
    it('should generate query hook with correct name', () => {
      const content = generator.generate(singleCollectionSchema)[0].content;
      expect(content).toContain('export function useUsersQuery');
    });

    it('should accept optional filter parameter', () => {
      const content = generator.generate(singleCollectionSchema)[0].content;
      expect(content).toContain('filter?: Partial<Users>');
    });

    it('should fetch from the correct API endpoint', () => {
      const content = generator.generate(singleCollectionSchema)[0].content;
      expect(content).toContain('/api/users');
    });

    it('should return data, loading, error', () => {
      const content = generator.generate(singleCollectionSchema)[0].content;
      expect(content).toContain('return { data, loading, error };');
    });
  });

  // ── useXxxById hook ────────────────────────────────────────────────

  describe('useXxxById hook', () => {
    it('should generate by-ID hook with correct name', () => {
      const content = generator.generate(singleCollectionSchema)[0].content;
      expect(content).toContain('export function useUsersById');
    });

    it('should accept id parameter', () => {
      const content = generator.generate(singleCollectionSchema)[0].content;
      expect(content).toContain('useUsersById(id: string)');
    });

    it('should fetch from /api/{collection}/{id}', () => {
      const content = generator.generate(singleCollectionSchema)[0].content;
      expect(content).toContain('/api/users/${id}');
    });
  });

  // ── useXxxMutation hook ────────────────────────────────────────────

  describe('useXxxMutation hook', () => {
    it('should generate mutation hook with correct name', () => {
      const content = generator.generate(singleCollectionSchema)[0].content;
      expect(content).toContain('export function useUsersMutation');
    });

    it('should include create operation with POST', () => {
      const content = generator.generate(singleCollectionSchema)[0].content;
      expect(content).toContain('const create = useCallback');
      expect(content).toContain("method: 'POST'");
      expect(content).toContain("'Content-Type': 'application/json'");
    });

    it('should include update operation with PATCH', () => {
      const content = generator.generate(singleCollectionSchema)[0].content;
      expect(content).toContain('const update = useCallback');
      expect(content).toContain("method: 'PATCH'");
    });

    it('should include remove operation with DELETE', () => {
      const content = generator.generate(singleCollectionSchema)[0].content;
      expect(content).toContain('const remove = useCallback');
      expect(content).toContain("method: 'DELETE'");
    });

    it('should return create, update, remove, loading, error', () => {
      const content = generator.generate(singleCollectionSchema)[0].content;
      expect(content).toContain('return { create, update, remove, loading, error };');
    });

    it('should use correct API endpoints in mutation operations', () => {
      const content = generator.generate(singleCollectionSchema)[0].content;
      // create posts to /api/users
      expect(content).toContain("'/api/users'");
      // update/remove to /api/users/${id}
      expect(content).toContain('/api/users/${id}');
    });
  });

  // ── Multi-collection ───────────────────────────────────────────────

  describe('multi-collection schemas', () => {
    it('should generate isolated hook files for each collection', () => {
      const schema: SchemaDefinition = {
        name: 'app',
        version: '1',
        collections: [
          { name: 'users', fields: [{ name: 'email', type: 'string' }] },
          { name: 'orders', fields: [{ name: 'total', type: 'number' }] },
        ],
      };
      const files = generator.generate(schema);
      expect(files).toHaveLength(2);

      const usersContent = files[0].content;
      const ordersContent = files[1].content;

      expect(usersContent).toContain('useUsersQuery');
      expect(usersContent).not.toContain('useOrdersQuery');
      expect(ordersContent).toContain('useOrdersQuery');
      expect(ordersContent).not.toContain('useUsersQuery');
    });

    it('should use correct API paths for each collection', () => {
      const schema: SchemaDefinition = {
        name: 'app',
        version: '1',
        collections: [
          { name: 'products', fields: [] },
          { name: 'categories', fields: [] },
        ],
      };
      const files = generator.generate(schema);
      expect(files[0].content).toContain('/api/products');
      expect(files[1].content).toContain('/api/categories');
    });
  });

  // ── Edge cases ─────────────────────────────────────────────────────

  describe('edge cases', () => {
    it('should handle collection with no fields', () => {
      const schema: SchemaDefinition = {
        name: 'app',
        version: '1',
        collections: [{ name: 'empty', fields: [] }],
      };
      const files = generator.generate(schema);
      expect(files).toHaveLength(1);
      const content = files[0].content;
      expect(content).toContain('export interface Empty');
      expect(content).toContain('useEmptyQuery');
      expect(content).toContain('useEmptyById');
      expect(content).toContain('useEmptyMutation');
    });
  });
});
