import { describe, expect, it } from 'vitest';
import { createTypeGenerator } from '../type-generator.js';
import type { SchemaDefinition } from '../types.js';

describe('TypeGenerator', () => {
  const generator = createTypeGenerator();

  // ── generate() ─────────────────────────────────────────────────────

  describe('generate()', () => {
    it('should produce a single types.ts file', () => {
      const schema: SchemaDefinition = {
        name: 'app',
        version: '1.0.0',
        collections: [{ name: 'items', fields: [{ name: 'label', type: 'string' }] }],
      };
      const files = generator.generate(schema);
      expect(files).toHaveLength(1);
      expect(files[0].path).toBe('types.ts');
      expect(files[0].overwrite).toBe(true);
    });

    it('should include auto-generated header comments', () => {
      const schema: SchemaDefinition = {
        name: 'app',
        version: '1.0.0',
        collections: [{ name: 'items', fields: [{ name: 'x', type: 'string' }] }],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('Auto-generated by @pocket/codegen-fullstack');
      expect(content).toContain('Do not edit manually');
    });

    it('should generate one interface per collection', () => {
      const schema: SchemaDefinition = {
        name: 'app',
        version: '1.0.0',
        collections: [
          { name: 'users', fields: [{ name: 'email', type: 'string' }] },
          { name: 'posts', fields: [{ name: 'title', type: 'string' }] },
          { name: 'comments', fields: [{ name: 'body', type: 'string' }] },
        ],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('export interface Users');
      expect(content).toContain('export interface Posts');
      expect(content).toContain('export interface Comments');
    });

    it('should capitalize the first letter of interface names', () => {
      const schema: SchemaDefinition = {
        name: 'app',
        version: '1.0.0',
        collections: [{ name: 'myItems', fields: [{ name: 'x', type: 'string' }] }],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('export interface MyItems');
    });

    it('should include the primary key (_id by default)', () => {
      const schema: SchemaDefinition = {
        name: 'app',
        version: '1.0.0',
        collections: [{ name: 'items', fields: [{ name: 'x', type: 'string' }] }],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('_id: string;');
    });

    it('should use custom primaryKey when provided', () => {
      const schema: SchemaDefinition = {
        name: 'app',
        version: '1.0.0',
        collections: [
          { name: 'items', fields: [{ name: 'x', type: 'string' }], primaryKey: 'uuid' },
        ],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('uuid: string;');
    });

    // ── Field type mapping ────────────────────────────────────────

    it('should map string type correctly', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [{ name: 'c', fields: [{ name: 'f', type: 'string', required: true }] }],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('f: string;');
    });

    it('should map number type correctly', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [{ name: 'c', fields: [{ name: 'f', type: 'number', required: true }] }],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('f: number;');
    });

    it('should map boolean type correctly', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [{ name: 'c', fields: [{ name: 'f', type: 'boolean', required: true }] }],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('f: boolean;');
    });

    it('should map date type to Date', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [{ name: 'c', fields: [{ name: 'f', type: 'date', required: true }] }],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('f: Date;');
    });

    it('should map object type to Record<string, unknown>', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [{ name: 'c', fields: [{ name: 'f', type: 'object', required: true }] }],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('f: Record<string, unknown>;');
    });

    it('should map array type to unknown[]', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [{ name: 'c', fields: [{ name: 'f', type: 'array', required: true }] }],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('f: unknown[];');
    });

    it('should map enum type to string', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [{ name: 'c', fields: [{ name: 'f', type: 'enum', required: true }] }],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('f: string;');
    });

    // ── Required / optional ───────────────────────────────────────

    it('should mark required fields without ? marker', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [{ name: 'c', fields: [{ name: 'req', type: 'string', required: true }] }],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('req: string;');
      expect(content).not.toContain('req?: string;');
    });

    it('should mark optional fields with ? marker', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [{ name: 'c', fields: [{ name: 'opt', type: 'string', required: false }] }],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('opt?: string;');
    });

    it('should treat fields without required property as optional', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [{ name: 'c', fields: [{ name: 'f', type: 'string' }] }],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('f?: string;');
    });

    // ── Timestamps & softDelete ───────────────────────────────────

    it('should include timestamp fields when timestamps=true', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [{ name: 'c', fields: [], timestamps: true }],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('createdAt?: Date;');
      expect(content).toContain('updatedAt?: Date;');
    });

    it('should NOT include timestamp fields when timestamps=false', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [{ name: 'c', fields: [], timestamps: false }],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).not.toContain('createdAt');
      expect(content).not.toContain('updatedAt');
    });

    it('should include deletedAt when softDelete=true', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [{ name: 'c', fields: [], softDelete: true }],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('deletedAt?: Date;');
    });

    it('should NOT include deletedAt when softDelete=false', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [{ name: 'c', fields: [], softDelete: false }],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).not.toContain('deletedAt');
    });

    // ── Relations ─────────────────────────────────────────────────

    it('should type one-to-one relation as the related collection type', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [
          {
            name: 'posts',
            fields: [
              {
                name: 'author',
                type: 'string',
                required: true,
                relation: { collection: 'users', type: 'one-to-one' },
              },
            ],
          },
        ],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('author: Users;');
    });

    it('should type one-to-many relation as an array', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [
          {
            name: 'users',
            fields: [
              {
                name: 'posts',
                type: 'string',
                required: true,
                relation: { collection: 'posts', type: 'one-to-many' },
              },
            ],
          },
        ],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('posts: Posts[];');
    });

    it('should type many-to-many relation as an array', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [
          {
            name: 'tags',
            fields: [
              {
                name: 'items',
                type: 'string',
                relation: { collection: 'items', type: 'many-to-many' },
              },
            ],
          },
        ],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('items?: Items[];');
    });

    // ── Complex schema ────────────────────────────────────────────

    it('should handle a collection with every field type', () => {
      const schema: SchemaDefinition = {
        name: 'full',
        version: '1.0.0',
        collections: [
          {
            name: 'everything',
            timestamps: true,
            softDelete: true,
            fields: [
              { name: 'text', type: 'string', required: true },
              { name: 'count', type: 'number' },
              { name: 'flag', type: 'boolean' },
              { name: 'when', type: 'date' },
              { name: 'data', type: 'object' },
              { name: 'list', type: 'array' },
              { name: 'status', type: 'enum' },
            ],
          },
        ],
      };
      const content = generator.generate(schema)[0].content;
      expect(content).toContain('text: string;');
      expect(content).toContain('count?: number;');
      expect(content).toContain('flag?: boolean;');
      expect(content).toContain('when?: Date;');
      expect(content).toContain('data?: Record<string, unknown>;');
      expect(content).toContain('list?: unknown[];');
      expect(content).toContain('status?: string;');
      expect(content).toContain('createdAt?: Date;');
      expect(content).toContain('updatedAt?: Date;');
      expect(content).toContain('deletedAt?: Date;');
    });

    it('should handle a collection with no fields', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [{ name: 'empty', fields: [] }],
      };
      const files = generator.generate(schema);
      expect(files).toHaveLength(1);
      const content = files[0].content;
      expect(content).toContain('export interface Empty');
      expect(content).toContain('_id: string;');
    });
  });

  // ── generateValidation() ───────────────────────────────────────────

  describe('generateValidation()', () => {
    it('should produce a single validation.ts file', () => {
      const schema: SchemaDefinition = {
        name: 'app',
        version: '1',
        collections: [{ name: 'items', fields: [{ name: 'x', type: 'string' }] }],
      };
      const files = generator.generateValidation(schema);
      expect(files).toHaveLength(1);
      expect(files[0].path).toBe('validation.ts');
      expect(files[0].overwrite).toBe(true);
    });

    it('should include header comments', () => {
      const schema: SchemaDefinition = {
        name: 'app',
        version: '1',
        collections: [{ name: 'items', fields: [] }],
      };
      const content = generator.generateValidation(schema)[0].content;
      expect(content).toContain('Auto-generated validation schemas');
    });

    it('should generate one validation function per collection', () => {
      const schema: SchemaDefinition = {
        name: 'app',
        version: '1',
        collections: [
          { name: 'users', fields: [{ name: 'email', type: 'string', required: true }] },
          { name: 'posts', fields: [{ name: 'title', type: 'string', required: true }] },
        ],
      };
      const content = generator.generateValidation(schema)[0].content;
      expect(content).toContain('export function validateUsers');
      expect(content).toContain('export function validatePosts');
    });

    it('should check required fields for undefined/null', () => {
      const schema: SchemaDefinition = {
        name: 'app',
        version: '1',
        collections: [
          { name: 'items', fields: [{ name: 'name', type: 'string', required: true }] },
        ],
      };
      const content = generator.generateValidation(schema)[0].content;
      expect(content).toContain('name is required');
      expect(content).toContain("=== undefined || data['name'] === null");
    });

    it('should validate string type', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [{ name: 'c', fields: [{ name: 'f', type: 'string' }] }],
      };
      const content = generator.generateValidation(schema)[0].content;
      expect(content).toContain("typeof data['f'] !== 'string'");
      expect(content).toContain('f must be a string');
    });

    it('should validate number type', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [{ name: 'c', fields: [{ name: 'f', type: 'number' }] }],
      };
      const content = generator.generateValidation(schema)[0].content;
      expect(content).toContain("typeof data['f'] !== 'number'");
      expect(content).toContain('f must be a number');
    });

    it('should validate boolean type', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [{ name: 'c', fields: [{ name: 'f', type: 'boolean' }] }],
      };
      const content = generator.generateValidation(schema)[0].content;
      expect(content).toContain("typeof data['f'] !== 'boolean'");
      expect(content).toContain('f must be a boolean');
    });

    it('should NOT add type validation for date/object/array/enum', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [
          {
            name: 'c',
            fields: [
              { name: 'd', type: 'date' },
              { name: 'o', type: 'object' },
              { name: 'a', type: 'array' },
              { name: 'e', type: 'enum' },
            ],
          },
        ],
      };
      const content = generator.generateValidation(schema)[0].content;
      expect(content).not.toContain('d must be a');
      expect(content).not.toContain('o must be a');
      expect(content).not.toContain('a must be a');
      expect(content).not.toContain('e must be a');
    });

    it('should return valid=true pattern and errors array in validation function', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [{ name: 'c', fields: [] }],
      };
      const content = generator.generateValidation(schema)[0].content;
      expect(content).toContain('const errors: string[] = [];');
      expect(content).toContain('return { valid: errors.length === 0, errors };');
    });

    it('should handle collection with no required fields', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [
          {
            name: 'items',
            fields: [
              { name: 'a', type: 'string', required: false },
              { name: 'b', type: 'number' },
            ],
          },
        ],
      };
      const content = generator.generateValidation(schema)[0].content;
      expect(content).not.toContain('is required');
    });

    it('should generate required + type validation together for a required string field', () => {
      const schema: SchemaDefinition = {
        name: 'a',
        version: '1',
        collections: [{ name: 'c', fields: [{ name: 'name', type: 'string', required: true }] }],
      };
      const content = generator.generateValidation(schema)[0].content;
      expect(content).toContain('name is required');
      expect(content).toContain('name must be a string');
    });
  });
});
