import type { GeneratedFile, SchemaDefinition } from './types.js';

export interface ApiGeneratorConfig {
  framework?: 'next' | 'express';
}

export interface ApiGenerator {
  generate(schema: SchemaDefinition): GeneratedFile[];
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * Creates a generator that produces REST API route handlers from a schema.
 */
export function createApiGenerator(config?: ApiGeneratorConfig): ApiGenerator {
  const framework = config?.framework ?? 'express';

  function generate(schema: SchemaDefinition): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    for (const collection of schema.collections) {
      if (framework === 'next') {
        files.push(generateNextRoute(collection.name, collection.fields));
      } else {
        files.push(generateExpressRoute(collection.name, collection.fields));
      }
    }

    return files;
  }

  function generateExpressRoute(
    name: string,
    fields: SchemaDefinition['collections'][number]['fields'],
  ): GeneratedFile {
    const typeName = capitalize(name);
    const requiredFields = fields.filter((f) => f.required);

    const lines: string[] = [
      '// Auto-generated by @pocket/codegen-fullstack',
      '// Do not edit manually',
      `import { Router } from 'express';`,
      '',
      `const router = Router();`,
      '',
      `// GET /api/${name} - List all`,
      `router.get('/', async (req, res) => {`,
      '  try {',
      `    // TODO: implement ${name} listing`,
      '    res.json([]);',
      '  } catch (err) {',
      '    res.status(500).json({ error: \'Internal server error\' });',
      '  }',
      '});',
      '',
      `// GET /api/${name}/:id - Get by ID`,
      `router.get('/:id', async (req, res) => {`,
      '  try {',
      `    const { id } = req.params;`,
      `    // TODO: implement ${name} get by id`,
      '    res.json({ _id: id });',
      '  } catch (err) {',
      '    res.status(500).json({ error: \'Internal server error\' });',
      '  }',
      '});',
      '',
      `// POST /api/${name} - Create`,
      `router.post('/', async (req, res) => {`,
      '  try {',
      `    const data = req.body;`,
    ];

    // Validation middleware inline
    if (requiredFields.length > 0) {
      lines.push(`    // Validation for ${typeName}`);
      for (const field of requiredFields) {
        lines.push(`    if (data['${field.name}'] === undefined) {`);
        lines.push(`      return res.status(400).json({ error: '${field.name} is required' });`);
        lines.push('    }');
      }
    }

    lines.push(`    // TODO: implement ${name} creation`);
    lines.push('    res.status(201).json(data);');
    lines.push('  } catch (err) {');
    lines.push("    res.status(500).json({ error: 'Internal server error' });");
    lines.push('  }');
    lines.push('});');
    lines.push('');
    lines.push(`// PATCH /api/${name}/:id - Update`);
    lines.push(`router.patch('/:id', async (req, res) => {`);
    lines.push('  try {');
    lines.push(`    const { id } = req.params;`);
    lines.push(`    const data = req.body;`);
    lines.push(`    // TODO: implement ${name} update`);
    lines.push('    res.json({ _id: id, ...data });');
    lines.push('  } catch (err) {');
    lines.push("    res.status(500).json({ error: 'Internal server error' });");
    lines.push('  }');
    lines.push('});');
    lines.push('');
    lines.push(`// DELETE /api/${name}/:id - Delete`);
    lines.push(`router.delete('/:id', async (req, res) => {`);
    lines.push('  try {');
    lines.push(`    const { id } = req.params;`);
    lines.push(`    // TODO: implement ${name} deletion`);
    lines.push('    res.json({ _id: id, deleted: true });');
    lines.push('  } catch (err) {');
    lines.push("    res.status(500).json({ error: 'Internal server error' });");
    lines.push('  }');
    lines.push('});');
    lines.push('');
    lines.push('export default router;');
    lines.push('');

    return {
      path: `routes/${name}.ts`,
      content: lines.join('\n'),
      overwrite: true,
    };
  }

  function generateNextRoute(
    name: string,
    fields: SchemaDefinition['collections'][number]['fields'],
  ): GeneratedFile {
    const typeName = capitalize(name);
    const requiredFields = fields.filter((f) => f.required);

    const lines: string[] = [
      '// Auto-generated by @pocket/codegen-fullstack',
      '// Do not edit manually',
      `import { NextRequest, NextResponse } from 'next/server';`,
      '',
      `// GET /api/${name}`,
      `export async function GET(req: NextRequest) {`,
      `  // TODO: implement ${name} listing`,
      '  return NextResponse.json([]);',
      '}',
      '',
      `// POST /api/${name}`,
      `export async function POST(req: NextRequest) {`,
      '  const data = await req.json();',
    ];

    if (requiredFields.length > 0) {
      lines.push(`  // Validation for ${typeName}`);
      for (const field of requiredFields) {
        lines.push(`  if (data['${field.name}'] === undefined) {`);
        lines.push(`    return NextResponse.json({ error: '${field.name} is required' }, { status: 400 });`);
        lines.push('  }');
      }
    }

    lines.push(`  // TODO: implement ${name} creation`);
    lines.push('  return NextResponse.json(data, { status: 201 });');
    lines.push('}');
    lines.push('');

    return {
      path: `app/api/${name}/route.ts`,
      content: lines.join('\n'),
      overwrite: true,
    };
  }

  return { generate };
}
