import type { GeneratedFile, SchemaDefinition } from './types.js';

export interface HooksGenerator {
  generate(schema: SchemaDefinition): GeneratedFile[];
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * Creates a generator that produces React hooks from a schema.
 */
export function createHooksGenerator(): HooksGenerator {
  function generate(schema: SchemaDefinition): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    for (const collection of schema.collections) {
      const name = capitalize(collection.name);
      const lines: string[] = [
        '// Auto-generated by @pocket/codegen-fullstack',
        '// Do not edit manually',
        `import { useState, useEffect, useCallback } from 'react';`,
        '',
        `export interface ${name} {`,
        `  _id: string;`,
      ];

      for (const field of collection.fields) {
        const optional = field.required ? '' : '?';
        lines.push(`  ${field.name}${optional}: ${fieldTypeToTs(field.type)};`);
      }

      lines.push('}');
      lines.push('');

      // useXxxQuery hook
      lines.push(`export function use${name}Query(filter?: Partial<${name}>) {`);
      lines.push(`  const [data, setData] = useState<${name}[]>([]);`);
      lines.push('  const [loading, setLoading] = useState(true);');
      lines.push('  const [error, setError] = useState<Error | null>(null);');
      lines.push('');
      lines.push('  useEffect(() => {');
      lines.push('    setLoading(true);');
      lines.push(`    fetch(\`/api/${collection.name}\` + (filter ? '?' + new URLSearchParams(filter as Record<string, string>).toString() : ''))`);
      lines.push('      .then((res) => res.json())');
      lines.push(`      .then((json) => { setData(json); setLoading(false); })`);
      lines.push(`      .catch((err) => { setError(err); setLoading(false); });`);
      lines.push('  }, [filter]);');
      lines.push('');
      lines.push('  return { data, loading, error };');
      lines.push('}');
      lines.push('');

      // useXxxById hook
      lines.push(`export function use${name}ById(id: string) {`);
      lines.push(`  const [data, setData] = useState<${name} | null>(null);`);
      lines.push('  const [loading, setLoading] = useState(true);');
      lines.push('  const [error, setError] = useState<Error | null>(null);');
      lines.push('');
      lines.push('  useEffect(() => {');
      lines.push('    setLoading(true);');
      lines.push(`    fetch(\`/api/${collection.name}/\${id}\`)`);
      lines.push('      .then((res) => res.json())');
      lines.push(`      .then((json) => { setData(json); setLoading(false); })`);
      lines.push(`      .catch((err) => { setError(err); setLoading(false); });`);
      lines.push('  }, [id]);');
      lines.push('');
      lines.push('  return { data, loading, error };');
      lines.push('}');
      lines.push('');

      // useXxxMutation hook
      lines.push(`export function use${name}Mutation() {`);
      lines.push('  const [loading, setLoading] = useState(false);');
      lines.push('  const [error, setError] = useState<Error | null>(null);');
      lines.push('');
      lines.push(`  const create = useCallback(async (data: Omit<${name}, '_id'>) => {`);
      lines.push('    setLoading(true);');
      lines.push('    try {');
      lines.push(`      const res = await fetch('/api/${collection.name}', {`);
      lines.push("        method: 'POST',");
      lines.push("        headers: { 'Content-Type': 'application/json' },");
      lines.push('        body: JSON.stringify(data),');
      lines.push('      });');
      lines.push('      return await res.json();');
      lines.push('    } catch (err) {');
      lines.push('      setError(err as Error);');
      lines.push('      throw err;');
      lines.push('    } finally {');
      lines.push('      setLoading(false);');
      lines.push('    }');
      lines.push('  }, []);');
      lines.push('');
      lines.push(`  const update = useCallback(async (id: string, data: Partial<${name}>) => {`);
      lines.push('    setLoading(true);');
      lines.push('    try {');
      lines.push(`      const res = await fetch(\`/api/${collection.name}/\${id}\`, {`);
      lines.push("        method: 'PATCH',");
      lines.push("        headers: { 'Content-Type': 'application/json' },");
      lines.push('        body: JSON.stringify(data),');
      lines.push('      });');
      lines.push('      return await res.json();');
      lines.push('    } catch (err) {');
      lines.push('      setError(err as Error);');
      lines.push('      throw err;');
      lines.push('    } finally {');
      lines.push('      setLoading(false);');
      lines.push('    }');
      lines.push('  }, []);');
      lines.push('');
      lines.push('  const remove = useCallback(async (id: string) => {');
      lines.push('    setLoading(true);');
      lines.push('    try {');
      lines.push(`      await fetch(\`/api/${collection.name}/\${id}\`, { method: 'DELETE' });`);
      lines.push('    } catch (err) {');
      lines.push('      setError(err as Error);');
      lines.push('      throw err;');
      lines.push('    } finally {');
      lines.push('      setLoading(false);');
      lines.push('    }');
      lines.push('  }, []);');
      lines.push('');
      lines.push('  return { create, update, remove, loading, error };');
      lines.push('}');
      lines.push('');

      files.push({
        path: `hooks/use${name}.ts`,
        content: lines.join('\n'),
        overwrite: true,
      });
    }

    return files;
  }

  return { generate };
}

function fieldTypeToTs(type: string): string {
  const typeMap: Record<string, string> = {
    string: 'string',
    number: 'number',
    boolean: 'boolean',
    date: 'Date',
    object: 'Record<string, unknown>',
    array: 'unknown[]',
    enum: 'string',
  };
  return typeMap[type] ?? 'unknown';
}
