/**
 * @pocket/codegen - Zod Schema Generator
 *
 * Generates Zod validation schemas from Pocket schema definitions.
 * Produces valid TypeScript code that imports from 'zod'.
 *
 * @module @pocket/codegen
 */

/**
 * A single field definition used by the Zod generator.
 */
export interface FieldDef {
  /** Field name */
  name: string;
  /** Field data type */
  type: string;
  /** Whether the field is required (default: false) */
  required?: boolean;
  /** Default value for the field */
  default?: unknown;
}

/**
 * A schema definition containing one or more collections.
 */
export interface SchemaDefinition {
  /** Collection definitions */
  collections: {
    /** Collection name */
    name: string;
    /** Fields in the collection */
    fields: FieldDef[];
  }[];
}

/**
 * Handle returned by {@link createZodGenerator}.
 */
export interface ZodGeneratorHandle {
  /** Generate a complete Zod file from a schema definition */
  generate(schema: SchemaDefinition): string;
  /** Generate a Zod schema for a single collection */
  generateCollection(name: string, fields: FieldDef[]): string;
}

/**
 * Map a simple type string to the corresponding Zod expression.
 */
function typeToZod(type: string): string {
  switch (type) {
    case 'string':
      return 'z.string()';
    case 'number':
      return 'z.number()';
    case 'boolean':
      return 'z.boolean()';
    case 'date':
      return 'z.coerce.date()';
    case 'array':
      return 'z.array(z.unknown())';
    case 'object':
      return 'z.record(z.string(), z.unknown())';
    default:
      return 'z.unknown()';
  }
}

/**
 * Convert a collection name to PascalCase.
 */
function toPascalCase(name: string): string {
  return name
    .split(/[-_\s]+/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/**
 * Convert a collection name to camelCase.
 */
function toCamelCase(name: string): string {
  const pascal = toPascalCase(name);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

/**
 * Generate a Zod schema string for a single collection.
 */
function buildCollectionSchema(name: string, fields: FieldDef[]): string {
  const schemaVar = `${toCamelCase(name)}Schema`;
  const typeName = toPascalCase(name);

  const fieldEntries = fields.map((field) => {
    let expr = typeToZod(field.type);

    if (!field.required) {
      expr += '.optional()';
    }

    if (field.default !== undefined) {
      expr += `.default(${JSON.stringify(field.default)})`;
    }

    return `  ${field.name}: ${expr}`;
  });

  const lines: string[] = [];

  lines.push(`/** Zod schema for ${typeName} */`);
  lines.push(`export const ${schemaVar} = z.object({`);
  lines.push(fieldEntries.join(',\n') + ',');
  lines.push(`});`);
  lines.push('');
  lines.push(`/** Inferred type for ${typeName} */`);
  lines.push(`export type ${typeName} = z.infer<typeof ${schemaVar}>;`);

  return lines.join('\n');
}

/**
 * Create a Zod generator that produces Zod validation schemas
 * from Pocket schema definitions.
 *
 * @returns A handle with `generate` and `generateCollection` methods
 *
 * @example
 * ```typescript
 * const generator = createZodGenerator();
 *
 * const code = generator.generate({
 *   collections: [{
 *     name: 'users',
 *     fields: [
 *       { name: 'email', type: 'string', required: true },
 *       { name: 'age', type: 'number' },
 *     ],
 *   }],
 * });
 * ```
 */
export function createZodGenerator(): ZodGeneratorHandle {
  return {
    generate(schema: SchemaDefinition): string {
      const lines: string[] = [];

      lines.push(`/**`);
      lines.push(` * Auto-generated Zod schemas`);
      lines.push(` *`);
      lines.push(` * DO NOT EDIT - This file is auto-generated by @pocket/codegen`);
      lines.push(` */`);
      lines.push('');
      lines.push(`import { z } from 'zod';`);
      lines.push('');

      for (const collection of schema.collections) {
        lines.push(buildCollectionSchema(collection.name, collection.fields));
        lines.push('');
      }

      return lines.join('\n');
    },

    generateCollection(name: string, fields: FieldDef[]): string {
      const lines: string[] = [];

      lines.push(`import { z } from 'zod';`);
      lines.push('');
      lines.push(buildCollectionSchema(name, fields));
      lines.push('');

      return lines.join('\n');
    },
  };
}
