import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'playground',
    'quick-reference',
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: false,
      items: [
        'concepts/architecture-overview',
        'concepts/local-first',
        'concepts/database-model',
        'concepts/reactive-queries',
        'concepts/storage-backends',
        'concepts/sync-architecture',
      ],
    },
    {
      type: 'category',
      label: 'Framework Integration',
      collapsed: false,
      items: [
        'guides/react-integration',
        'guides/vue-integration',
        'guides/svelte-integration',
        'guides/solid-integration',
        'guides/angular-integration',
      ],
    },
    {
      type: 'category',
      label: 'Mobile & Desktop',
      collapsed: false,
      items: [
        'guides/react-native',
        'guides/expo-integration',
        'guides/electron-integration',
        'guides/tauri-integration',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/offline-first-app',
        'guides/sync-setup',
        'guides/conflict-resolution',
        'guides/schema-validation',
        'guides/zod-schemas',
        'guides/indexing',
        'guides/relationships',
        'guides/plugins',
        'guides/full-text-search',
        'guides/migrations',
        'guides/vectors-ai',
        'guides/encryption',
        'guides/crdts',
        'guides/selective-sync',
        'guides/ttl-expiration',
        'guides/data-seeding',
        'guides/edge-runtime',
        'guides/observability',
        'guides/devtools',
        'guides/migrating-from-other-databases',
      ],
    },
    {
      type: 'category',
      label: 'Best Practices',
      collapsed: true,
      items: ['guides/testing', 'guides/performance', 'guides/security'],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      items: [
        'api/database',
        'api/collection',
        'api/query-builder',
        'api/sync-engine',
        'api/react-hooks',
        'api/cli',
        'api/error-codes',
      ],
    },
    'troubleshooting',
    'faq',
    'comparison',
    'changelog',
    'roadmap',
    'contributing',
    {
      type: 'category',
      label: 'Architecture Decisions',
      collapsed: true,
      items: [
        'adr/README',
        'adr/adr-001-local-first-architecture',
        'adr/adr-002-rxjs-for-reactivity',
        'adr/adr-003-pluggable-storage-adapters',
        'adr/adr-004-vector-clocks-for-sync',
        'adr/adr-005-monorepo-structure',
        'adr/adr-006-plugin-system-architecture',
        'adr/adr-007-event-reduce-algorithm',
        'adr/adr-008-react-hooks-integration',
        'adr/adr-009-transport-layer-abstraction',
        'adr/adr-010-optimistic-updates-with-rollback',
        'adr/adr-011-bundle-size-constraints',
        'adr/adr-012-umbrella-package-pattern',
      ],
    },
  ],
};

export default sidebars;
